### ISSUE TITLE
Update to Fody Version 2

### ISSUE THREAD

**Issue by SimonCropp** [Dresel/MethodCache#15]
Fody Version 2 is out and you will need to do an update for your addin to be usable with it

Specifically:

 * Update to the newest Fody.Cecil nuget
 * Change the min dependency range for Fody to be at least 2.0

 Please ping me if u need help

**Comment by Dresel** [comment]
Sorry for my late reply. Will update asap. Thanks for mentioning.

**Comment by meledictas** [comment]
Hi, 

Latest release from nuget doesn't seem to work. I'm using Visual Studio Community 2017 version 15.2.  Following below steps:

1. Install MethodCache.Fody via Nuget (MethodCache.Fody.1.5.0 is installed)
2. Add <MethodCache /> in the Weavers.xml
3. Try build and got Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
4. Try upgrade Fody to version 2.0.9 and got error MSBUILD : error : Fody: The weaver assembly 'MethodCache.Fody, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll (cecilReference.Version). At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0.

Downgrade Fody to version 1.29.4.0 then can build successfully.

Thanks,

**Comment by Dresel** [comment]
@SimonCropp

MethodCache.Fody 1.5.1 now defines Fody < 2.0.0. Since NuGet Client installs Fody 1.28.3 it breaks on VS 2017. Any thoughts on this? Should I set the minimum version to 1.29.1?

MethodCache.Fody 2.0.0-alpha1 now references Mono.Cecil > 0.10 and should be compatible with Fody >= 2.0.0.

Not related to this issue, but might I ask you a different question? Now that Fody supports .NET Standard what will be necessary to support this? I guess it does not only affect the [MethodCache.Attributes](https://github.com/Dresel/MethodCache/tree/master/MethodCache.Attributes) PCL but also the Weaver assembly itself (e.g. [ReferenceFinder.cs](https://github.com/Dresel/MethodCache/blob/master/MethodCache.Fody/ReferenceFinder.cs))?

@meledictas:

You can try

    Install-Package MethodCache.Fody -Version 2.0.0-alpha1

if you want to use a newer version of Fody.

**Comment by halittiryaki** [comment]
@SimonCropp 

tried all kind of versions combinations via nuget, but cant get rid of the exception.

> Severity Code Description Project File	Line	Suppression State Error Fody: The weaver assembly 'MethodDecorator.Fody, Version=0.9.0.4, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll (cecilReference.Version). At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0.				

current installed package versions:

- Fody 2.1.3
- FodyCecil 2.1.3
- MethodDecorator.Fody 0.9.0.6
- MethodDecorator.Fody.VS2015 0.9.0.7

thanks

**Comment by shtse8** [comment]
any updates for the stable release?

**Comment by Dresel** [comment]
Does `2.0.0-alpha1` not work for you?

**Comment by shtse8** [comment]
It works. 
I am choosing between Fody vs P# for caching and propertynotify.
I like Fody very much, but I can't find a good caching active package.
So I want to know when will the stable version be released? or is this github still active?
Thanks for your contribution.

**Comment by Dresel** [comment]
I'm not actively adding new features if it is that what you mean, so that is why this repo might look inactive. But when bug requests come in, I'm usually going to fix them asap.

This version is stable as far as I know (at least there are no open issues if #14 is considered as feature request), so the only thing I could do is changing the version number from `2.0.0-alpha1` to `2.0.0`.

**Comment by shtse8** [comment]
@Dresel That's great and what I want.
